[tool.ruff]
extend-exclude = ['venv', 'env', 'migrations']

[tool.ruff.lint]
select = [
    'F',    # pyflakes
    'E',    # pycodestyle
    'W',    # pycodestyle
    'I',    # isort
    'UP',   # pyupgrade
    'B',    # flake8-bugbear
    'C',    # flake8-comprehensions
    'DTZ',  # flake8-datetimez
    'RUF',  # ruff
    'N',    # pep8-naming
]

ignore = [
    'C901', # complex structure, not needed
]

[tool.ruff.lint.per-file-ignores]
'__init__.py' = [
    'F401', # unused import
    'E402', # module import not at top of file
]

[tool.pyright]
reportIncompatibleVariableOverride = false

